#!/bin/sh

# change to the directory where the script sits
cd $(dirname $0)

if [ -f ../../tale/__init__.py ];
then
   #use the tail library found in the project directory a few dirs up
   if [ -z ${PYTHONPATH} ]; then
      export PYTHONPATH=../..
   else
      export PYTHONPATH=../..:${PYTHONPATH}
   fi
fi

# start the game
python3 -m tale.main --game . $*
